Repository cristianbote/goober, pull requests merged in 2020-01, with the labels that each got.

#81 (chore) Added the gatsby-plugin-goober (fixes #44)
  packages/gatsby-plugin-goober/README.md
  packages/gatsby-plugin-goober/gatsby-browser.js
  packages/gatsby-plugin-goober/gatsby-ssr.js
  packages/gatsby-plugin-goober/index.js
  packages/gatsby-plugin-goober/package.json
Labels: chore, feature

#92 (fix) Fix typing for multiple tagged templates functions (Fixes #91)
  goober.d.ts
  ts-tests/test-api.tsx
Labels: bug

#94 goober babel-macro
  packages/babel-macro-goober/README.md
  packages/babel-macro-goober/index.js
  packages/babel-macro-goober/package.json
Labels: feature
