Repository cristianbote/goober, pull requests merged in 2020-10, with the labels that each got.

#183 (fix) true nested handler
  package-lock.json
  package.json
  src/core/__tests__/parse.test.js
  src/core/parse.js
Labels: bug

#184 (feat) Improve parse and size shave
  src/core/__tests__/parse.test.js
  src/core/parse.js
Labels: code golf, feature

#188 (feat) Add support for object outputs in tagged templates
  package-lock.json
  package.json
  src/__tests__/integrations.test.js
  src/core/__tests__/compile.test.js
  src/core/compile.js
Labels: feature

#190 (chore) Improve package quality score by adding exports map
  package.json
Labels: chore

#194 Add the types for forwardRef argument to styled()
  README.md
  goober.d.ts
  ts-tests/test-api.tsx
Labels: bug

#195 fix package entry points
  package.json
Labels: bug
